server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/bvp
    username: breeze
    password: breeze

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect