services:
  postgres:
    container_name: bvp
    image: postgres
    environment:
      POSTGRES_USER: breeze
      POSTGRES_PASSWORD: breeze
      PGDATA: /data/postgres

    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - bvp-ms
    restart: unless-stopped

  keycloak:
    container_name: keycloak-bvp
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - bvp-ms
    command:
      - "start-dev"

  pgadmin:
    container_name: bvp-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-breeze@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-breeze}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bvp-ms
    restart: unless-stopped

networks:
  bvp-ms:
    driver: bridge

volumes:
  postgres:
  pgadmin: